### ISSUE TITLE
Add mark playlist/albums/songs for auto export 

### ISSUE THREAD

**Issue by J05HI** [jcgruenhage/PlayMusicExporter#39] opened 2017-08-11 16:16 UTC
The title says everything ;)

**Comment by jcgruenhage** [comment] 2017-08-11 19:16
There's already an issue for that below, so duplicate of #17.

**Closed as completed by jcgruenhage** 2017-08-11 19:16 UTC

**Comment by J05HI** [comment] 2017-08-11 19:21
Oh okay, I've seen it but was not sure about it
